import '../png/cross.png'
import '../png/done.png'
import '../png/edit.png'
import '../png/basket.png'
import '../png/canel.png'
import '../png/wheel.png'
import '../png/camera.png'
import '../png/contacts.png'
import '../png/exit.png'
import '../png/ninja.png'
import '../png/password.png'
import '../png/tools.png'
import '../png/user.png'
import '../png/chat.png'
import '../png/back.png'


import '../scss/main.scss'
import './ws'
import './edit'
import './settings_menu'
import './display_avatar'
